# Generated by Django 5.1.5 on 2025-02-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
