# Generated by Django 5.1.5 on 2025-02-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagar_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
