# Generated by Django 5.1.5 on 2025-02-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_pagar_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pagar_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
