# Generated by Django 5.1.5 on 2025-02-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interes_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
